[package]
name = "tokio-zmq"
description = "Provides Futures abstractions for ZeroMQ on the Tokio event-loop"
version = "0.1.2"
license = "GPL-3.0"
authors = ["Riley Trautman <asonix.dev@gmail.com>"]
repository = "https://github.com/asonix/tokio-zmq"
readme = "README.md"
keywords = ["zmq", "zeromq", "futures", "tokio"]

[dependencies]
zmq = "0.8"
futures = "0.1"
tokio-core = "0.1"
tokio-file-unix = "0.4"
log = "0.4"

[dev-dependencies]
env_logger = "0.4"
